services:
  ocl-cache:
    #build: .
    image: ghcr.io/cheminfo/ocl-cache:v1.1.0
    restart: unless-stopped
    ulimits:
      core: 0
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    volumes:
      - ./sqlite:/node/sqlite
    ports:
      - 127.0.0.1:20822:20822

  process-sdf:
    #build: .
    image: ghcr.io/cheminfo/ocl-cache:v1.1.0
    restart: always
    ulimits:
      core: 0
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    volumes:
      - ./sqlite:/node/sqlite
      - ./data/sdf:/node/data/sdf
      - ./data/smiles:/node/data/smiles
    command: npm run processSDF
